.TH DUBLIN-TRACEROUTE "1" "May 2016" "dublin-traceroute 0.2" "User Commands"
.SH NAME
dublin-traceroute \- Dublin Traceroute
.SH SYNOPSIS
.B dublin-traceroute \fB<target hostname / IP address>\fR
.SH "REPORTING BUGS"
https://github.com/insomniacslk/dublin-traceroute/issues
.SH "SEE ALSO"
https://dublin-traceroute.net
.SH AUTHOR
dublin-traceroute was written by Andrea Barberio <insomniac@slackware.it>
